.TH FTPSYNC.CONF 5 "2026-03-27" "ctxos-core 1.0.0" "CTX OS Manual"
.SH NAME
ftpsync.conf \- configuration for ftpsync
.SH DESCRIPTION
Shell script sourced by ftpsync to set configuration variables.
.SH VARIABLES
.TP
.B RSYNC_PATH
Path to rsync binary.
.TP
.B ARCHIVE_BASE
Base directory of the local archive.
.TP
.B TO
Destination directory.
.TP
.B LOGDIR
Log directory.
.TP
.B LOCKDIR
Lock file directory.
.SH SEE ALSO
.BR ftpsync (1)
