.TH RUNMIRRORS.CONF 5 "2026-03-27" "ctxos-core 1.0.0" "CTX OS Manual"
.SH NAME
runmirrors.conf \- configuration for runmirrors
.SH DESCRIPTION
Shell script sourced by runmirrors to set configuration variables.
.SH VARIABLES
.TP
.B MIRRORS
Path to the mirrors file.
.TP
.B PUSHKIND
Push type: all, stage2, mhop.
.TP
.B MAILTO
Email address for notifications.
.SH SEE ALSO
.BR runmirrors (1),
.BR runmirrors.mirror (5)
